name: daystodieutils
description: 七日杀工具
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  adaptive_dialog: ^1.9.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  logger: ^2.0.1
  fast_cached_network_image: ^1.2.0
  shared_preferences: ^2.2.0
  synchronized: ^3.1.0
  infinite_scroll_pagination: ^4.0.0
  # banner
  card_swiper: ^3.0.1
  image_network: ^2.5.4+1
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  path_provider: ^2.1.1
  event_bus: ^2.0.0
  url_launcher: ^6.1.14
  url_launcher_web: ^2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
